[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/.netlify/identity/verify"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301