backend:
  name: github
  repo: KareemElGebaly/yaraelmasri
  branch: main
  auth_type: implicit

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "المنشورات"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الوصف", name: "description", widget: "string" }
      - { label: "تاريخ النشر", name: "pubDate", widget: "datetime" }
      - { label: "الفئة", name: "category", widget: "string" }
      - { label: "الصورة", name: "image", widget: "image" }
      - { label: "المحتوى", name: "body", widget: "markdown" }